package Exception_handling;


class program14_a{

    void m1(){
        System.out.println("In m1");
    }
    private void m2(){

    }
}
